return
{
	 {
        name = "blue_singlefirework",
        bank = "firework",
        build = "blue_fireworks",
        anim = "single_firework",
		lightoverride = true,
        sound = "dontstarve/common/shrine/sadwork_fire",
        sound2 = "dontstarve/common/shrine/sadwork_explo",
        sounddelay2 = 26/30,
        fn = function() TheWorld:PushEvent("screenflash", .65) end,
        fntime = 26/30,
		bloom = true,
    },
    {
        name = "blue_multifirework",
        bank = "firework",
        build = "blue_fireworks",
        anim = "multi_firework",
		lightoverride = true,
        sound = "dontstarve/common/shrine/sadwork_fire",
        sound2 = "dontstarve/common/shrine/firework_explo",
        sounddelay2 = 26/30,
        fn = function() TheWorld:PushEvent("screenflash", 1) end,
        fntime = 26/30,
		bloom = true,
    },
	{
        name = "red_singlefirework",
        bank = "firework",
        build = "red_fireworks",
        anim = "single_firework",
		lightoverride = true,
        sound = "dontstarve/common/shrine/sadwork_fire",
        sound2 = "dontstarve/common/shrine/sadwork_explo",
        sounddelay2 = 26/30,
        fn = function() TheWorld:PushEvent("screenflash", .65) end,
        fntime = 26/30,
		bloom = true,
    },
    {
        name = "red_multifirework",
        bank = "firework",
        build = "red_fireworks",
        anim = "multi_firework",
		lightoverride = true,
        sound = "dontstarve/common/shrine/sadwork_fire",
        sound2 = "dontstarve/common/shrine/firework_explo",
        sounddelay2 = 26/30,
        fn = function() TheWorld:PushEvent("screenflash", 1) end,
        fntime = 26/30,
		bloom = true,
    },
	{
        name = "purple_singlefirework",
        bank = "firework",
        build = "purple_fireworks",
        anim = "single_firework",
		lightoverride = true,
        sound = "dontstarve/common/shrine/sadwork_fire",
        sound2 = "dontstarve/common/shrine/sadwork_explo",
        sounddelay2 = 26/30,
        fn = function() TheWorld:PushEvent("screenflash", .65) end,
        fntime = 26/30,
		bloom = true,
    },
    {
        name = "purple_multifirework",
        bank = "firework",
        build = "purple_fireworks",
        anim = "multi_firework",
		lightoverride = true,
        sound = "dontstarve/common/shrine/sadwork_fire",
        sound2 = "dontstarve/common/shrine/firework_explo",
        sounddelay2 = 26/30,
        fn = function() TheWorld:PushEvent("screenflash", 1) end,
        fntime = 26/30,
		bloom = true,
    },
	{
        name = "special_smoke",
        bank = "small_puff",
        build = "special_smoke",
        anim = "puff",
        sound = "dontstarve/common/deathpoof",
    },
	{
        name = "forest_seed_fx",
        bank = "collapse",
        build = "forest_seed_fx",
        anim = "collapse_large",
        sound = "dontstarve/sanity/creature1/dissappear",
    },
	{
        name = "green_spell_fx",
        bank = "dragonfly_ground_fx",
        build = "green_spell_fx",
        anim = "idle",
		transform = Vector3(1.5, 2, 1.5),
        sound = "dontstarve/sanity/creature1/dissappear",
		bloom = true,
    },
	{
        name = "blue_spell_fx",
        bank = "dragonfly_ground_fx",
        build = "blue_spell_fx",
        anim = "idle",
		transform = Vector3(1.5, 2, 1.5),
        sound = "dontstarve/sanity/creature1/dissappear",
		bloom = true,
    },
	{
        name = "red_spell_fx",
        bank = "dragonfly_ground_fx",
        build = "red_spell_fx",
        anim = "idle",
		transform = Vector3(1.5, 2, 1.5),
        sound = "dontstarve/sanity/creature1/dissappear",
		bloom = true,
    },
	{
        name = "white_spell_fx",
        bank = "dragonfly_ground_fx",
        build = "white_spell_fx",
        anim = "idle",
		transform = Vector3(1.5, 2, 1.5),
        sound = "dontstarve/sanity/creature1/dissappear",
		bloom = true,
    },
	{
        name = "yellow_spell_fx",
        bank = "dragonfly_ground_fx",
        build = "yellow_spell_fx",
        anim = "idle",
		transform = Vector3(1.5, 2, 1.5),
        sound = "dontstarve/sanity/creature1/dissappear",
		bloom = true,
    },
	{
        name = "black_spell_fx",
        bank = "dragonfly_ground_fx",
        build = "black_spell_fx",
        anim = "idle",
		transform = Vector3(1.5, 2, 1.5),
        sound = "dontstarve/sanity/creature1/dissappear",
		bloom = true,
    },
	
}